name: Deploy Vite app from subfolder to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section grants necessary permissions
      contents: write # Allows pushing content to the repository
      pages: write # Specifically for GitHub Pages deployments
      id-token: write # Recommended for OIDC (OpenID Connect)

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: classnotesapp

      - name: Build
        run: npm run build
        working-directory: classnotesapp

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: classnotesapp/dist
          force_orphan: true